final List<Map<String, dynamic>> profiles = [
  {
    "name": "Armaan Khan",
    "age": 20,
    "community": "shelter nest",
    "post": "member",
    "remark": "no",
  },
  {
    "name": "Sarah Johnson",
    "age": 25,
    "community": "Harmony Haven",
    "post": "Leader",
    "remark": "yes",
  },
  {
    "name": "Raj Patel",
    "age": 30,
    "community": "Unity Village",
    "post": "volunteer",
    "remark": "yes",
  },
  {
    "name": "Emily Davis",
    "age": 22,
    "community": "Hope Haven",
    "post": "member",
    "remark": "no",
  },
  {
    "name": "John Smith",
    "age": 28,
    "community": "Green Oasis",
    "post": "volunteer",
    "remark": "yes",
  },
  {
    "name": "Linda White",
    "age": 35,
    "community": "Rainbow Refuge",
    "post": "leader",
    "remark": "no",
  },
  {
    "name": "Michael Brown",
    "age": 29,
    "community": "Sunshine Shelter",
    "post": "member",
    "remark": "yes",
  },
  {
    "name": "Ava Robinson",
    "age": 24,
    "community": "Serenity Haven",
    "post": "volunteer",
    "remark": "no",
  },
  {
    "name": "Daniel Garcia",
    "age": 31,
    "community": "Tranquil Retreat",
    "post": "member",
    "remark": "yes",
  },
  {
    "name": "Olivia Lee",
    "age": 27,
    "community": "Hope Haven",
    "post": "volunteer",
    "remark": "no",
  },
];
