import 'package:community_app/imageurl.dart';
import 'package:community_app/list_of_community.dart';

List<Community> communityListsData = [
  Community(
      "Tech Enthusiasts",
      "A community for tech enthusiasts to discuss the latest trends and innovations in technology.",
      5,
      "San Francisco, USA",
      2500,
      800,
      imagesOfCommunity[0]),
  Community(
    "Environmental Activists",
    "A community of passionate individuals working to protect the environment.",
    4,
    "New York City, USA",
    1200,
    300,
    imagesOfCommunity[1],
  ),
  Community(
    "Fitness Fanatics",
    "A community for fitness enthusiasts to share workouts, tips, and success stories.",
    4,
    "Austin, USA",
    2200,
    750,
    imagesOfCommunity[2],
  ),
  Community(
    "Music Lovers Club",
    "A community of music enthusiasts discussing their favorite songs and artists.",
    5,
    "Nashville, USA",
    1800,
    600,
    imagesOfCommunity[3],
  ),
  Community(
    "Coding Wizards",
    "A community of coding experts sharing coding challenges and solutions.",
    4,
    "Seattle, USA",
    1600,
    400,
    imagesOfCommunity[4],
  ),
  Community(
    "Travel Explorers",
    "A community of avid travelers sharing their travel experiences and tips.",
    4,
    "Denver, USA",
    1200,
    300,
    imagesOfCommunity[5],
  ),
  Community(
    "Animal Lovers Society",
    "A community of animal enthusiasts advocating for animal welfare and rescue.",
    3,
    "Portland, USA",
    1400,
    500,
    imagesOfCommunity[6],
  ),
  Community(
    "Healthy Living Enthusiasts",
    "A community dedicated to promoting healthy lifestyles through fitness and nutrition.",
    3,
    "Los Angeles, USA",
    1800,
    600,
    imagesOfCommunity[7],
  ),
  Community(
    "Artistic Creators",
    "A community of artists and creators sharing their work and inspiring each other.",
    5,
    "Chicago, USA",
    1500,
    500,
    imagesOfCommunity[8],
  ),
  Community(
    "Book Lovers Club",
    "A community of bookworms who discuss their favorite books and authors.",
    4,
    "Boston, USA",
    900,
    200,
    imagesOfCommunity[9],
  ),
  Community(
    "Local Foodies",
    "A community of food enthusiasts exploring local culinary delights and sharing recommendations.",
    4,
    "Miami, USA",
    1300,
    400,
    imagesOfCommunity[10],
  ),
  Community(
      "Fitness Fanatics",
      "Join us in achieving your fitness goals! We offer workout tips, nutrition advice, and support.",
      8,
      "New York City, USA",
      1500,
      600,
      imagesOfCommunity[11]),
  Community(
    "Art Lovers",
    "Explore the world of art with like-minded individuals. Share your creations and get inspired.",
    12,
    "Paris, France",
    1800,
    700,
    imagesOfCommunity[12],
  ),
  Community(
    "Cooking Enthusiasts",
    "Discover the joy of cooking with our community. Share recipes and cooking hacks.",
    7,
    "London, UK",
    1200,
    400,
    imagesOfCommunity[13],
  ),
  Community(
    "Photography Club",
    "Capture the beauty of the world through the lens. Share your photos and photography tips.",
    10,
    "Tokyo, Japan",
    2200,
    900,
    imagesOfCommunity[14],
  ),
  Community(
    "Travel Explorers",
    "Embark on exciting journeys and share your travel experiences with fellow explorers.",
    6,
    "Sydney, Australia",
    2800,
    1000,
    imagesOfCommunity[6],
  ),
  Community(
    "Music Lovers",
    "Celebrate the magic of music. Discuss your favorite genres, artists, and concerts.",
    9,
    "Los Angeles, USA",
    1900,
    750,
    imagesOfCommunity[3],
  ),
  Community(
      "Gaming Geeks",
      "Level up your gaming skills and stay updated on the gaming world's latest developments.",
      15,
      "Seoul, South Korea",
      3500,
      1200,
      imagesOfCommunity[14]),
  Community(
      "Startup Enthusiasts",
      "Connect with entrepreneurs and innovators. Discuss startups, business strategies, and more.",
      11,
      "Berlin, Germany",
      2000,
      850,
      imagesOfCommunity[0]),
  Community(
      "Bookworms",
      "Dive into the world of literature. Share your reading lists and book recommendations.",
      8,
      "Toronto, Canada",
      1400,
      500,
      "https://img.freepik.com/free-psd/3d-landscape-with-fairytale-elements_23-2150048919.jpg?size=626&ext=jpg&ga=GA1.1.1609798635.1690365622&semt=ais"),
];
